# Generated by Django 4.2.4 on 2023-08-02 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=10)),
                ('sigungu', models.CharField(max_length=10)),
                ('month', models.IntegerField()),
                ('place', models.CharField(max_length=10)),
                ('cause', models.CharField(max_length=30)),
                ('report_arrival_hour', models.IntegerField()),
                ('report_arrival_min', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Beach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beach_name', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=10)),
                ('sigungu', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='LifesavingEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_long', models.FloatField()),
                ('equipment_lat', models.FloatField()),
                ('spot', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SafetyInfra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=10)),
                ('fs_cnt', models.IntegerField()),
                ('sc_cnt', models.IntegerField()),
                ('fb_cnt', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WindSpeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('wind_speed', models.IntegerField()),
                ('beach_id', models.OneToOneField(db_column='beach_id', on_delete=django.db.models.deletion.CASCADE, to='example.beach')),
            ],
        ),
        migrations.CreateModel(
            name='WindDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('wind_direction', models.CharField(max_length=10)),
                ('beach_id', models.OneToOneField(db_column='beach_id', on_delete=django.db.models.deletion.CASCADE, to='example.beach')),
            ],
        ),
        migrations.CreateModel(
            name='WaveHeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('wave_height', models.FloatField()),
                ('beach_id', models.OneToOneField(db_column='beach_id', on_delete=django.db.models.deletion.CASCADE, to='example.beach')),
            ],
        ),
        migrations.CreateModel(
            name='RainfallScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rain_score', models.FloatField()),
                ('rain_prob', models.FloatField()),
                ('date', models.DateField()),
                ('beach_name', models.CharField(max_length=15)),
                ('beach_id', models.OneToOneField(db_column='beach_id', on_delete=django.db.models.deletion.CASCADE, to='example.beach')),
            ],
        ),
        migrations.CreateModel(
            name='MaxTemperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day_max_temp', models.FloatField()),
                ('beach_id', models.OneToOneField(db_column='beach_id', on_delete=django.db.models.deletion.CASCADE, to='example.beach')),
            ],
        ),
        migrations.CreateModel(
            name='JellyfishScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jellyfish_score', models.IntegerField()),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=10)),
                ('beach_id', models.OneToOneField(db_column='beach_id', on_delete=django.db.models.deletion.CASCADE, to='example.beach')),
            ],
        ),
        migrations.CreateModel(
            name='BeachScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beach_name', models.CharField(max_length=15)),
                ('water_score', models.FloatField()),
                ('soil_score', models.FloatField()),
                ('facility_score', models.FloatField()),
                ('location', models.CharField(max_length=10)),
                ('beach_id', models.OneToOneField(db_column='beach_id', on_delete=django.db.models.deletion.CASCADE, to='example.beach')),
            ],
        ),
        migrations.CreateModel(
            name='BeachInfra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shower_room', models.IntegerField()),
                ('toilet', models.IntegerField()),
                ('dressing_room', models.IntegerField()),
                ('watch_tower', models.IntegerField()),
                ('tap_water', models.IntegerField()),
                ('beach_id', models.ForeignKey(db_column='beach_id', on_delete=django.db.models.deletion.CASCADE, to='example.beach')),
            ],
        ),
    ]
