# Generated by Django 4.2.4 on 2023-08-03 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accident',
            name='report_arrival_hour',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='report_arrival_min',
        ),
    ]
