# Generated by Django 4.2.4 on 2023-08-03 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='accident',
            table='Accident',
        ),
        migrations.AlterModelTable(
            name='beach',
            table='Beach',
        ),
        migrations.AlterModelTable(
            name='beachinfra',
            table='BeachInfra',
        ),
        migrations.AlterModelTable(
            name='beachscore',
            table='BeachScore',
        ),
        migrations.AlterModelTable(
            name='jellyfishscore',
            table='JellyfishScore',
        ),
        migrations.AlterModelTable(
            name='lifesavingequipment',
            table='LifesavingEquipment',
        ),
        migrations.AlterModelTable(
            name='maxtemperature',
            table='MaxTemperature',
        ),
        migrations.AlterModelTable(
            name='rainfallscore',
            table='RainfallScore',
        ),
        migrations.AlterModelTable(
            name='safetyinfra',
            table='SafetyInfra',
        ),
        migrations.AlterModelTable(
            name='waveheight',
            table='WaveHeight',
        ),
        migrations.AlterModelTable(
            name='winddirection',
            table='WindDirection',
        ),
        migrations.AlterModelTable(
            name='windspeed',
            table='WindSpeed',
        ),
    ]
