# Generated by Django 4.2.4 on 2023-08-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_remove_accident_report_arrival_hour_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beach',
            name='id',
        ),
        migrations.AddField(
            model_name='beach',
            name='beach_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
