# Generated by Django 4.2.4 on 2023-08-03 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_remove_beach_id_beach_beach_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beachscore',
            name='beach_id',
            field=models.ForeignKey(db_column='beach_id', on_delete=django.db.models.deletion.CASCADE, to='example.beach'),
        ),
        migrations.AlterField(
            model_name='jellyfishscore',
            name='beach_id',
            field=models.ForeignKey(db_column='beach_id', on_delete=django.db.models.deletion.CASCADE, to='example.beach'),
        ),
        migrations.AlterField(
            model_name='rainfallscore',
            name='beach_id',
            field=models.ForeignKey(db_column='beach_id', on_delete=django.db.models.deletion.CASCADE, to='example.beach'),
        ),
    ]
