# Generated by Django 4.2.4 on 2023-08-03 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0004_alter_beachscore_beach_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beach',
            old_name='beach_id',
            new_name='id',
        ),
    ]
